# cargo

# [[file:~/Workspace/Programming/gosh-rs/core/gosh-core.note::*cargo][cargo:1]]
[package]
name = "gosh-core"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]
description = "A meta package for managing shared packages in gosh project"
homepage = "https://github.com/gosh-rs/core"
repository = "https://github.com/gosh-rs/core"
license = "MIT OR Apache-2.0"

[dependencies]
vecfx = { version="0.0.8", features = ["nalgebra"] }
gut = { version = "0.0.8", package = "gchemol-gut" }
text-parser = { version = "0.0.7", package = "gchemol-parser" }
gchemol = { version="0.0.38" }

[dev-dependencies]
# cargo:1 ends here
