# cargo

# [[file:~/Workspace/Programming/gosh-rs/core/gosh-core.note::*cargo][cargo:1]]
[package]
name = "gosh-core"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
vecfx = { git = "https://github.com/gchemol/vecfx.git", features = ["nalgebra"] }
gchemol = {git = "https://github.com/ybyygu/gchemol.git"}
guts = { git = "https://github.com/ybyygu/guts.git" }
#vecfx = { path = "/home/ybyygu/Workspace/Programming/gchemol-rs/vecfx" }
#gchemol = { path = "/home/ybyygu/Workspace/Programming/gchemol-rs/gchemol/gchemol" }
#guts = { path = "/home/ybyygu/Workspace/Programming/guts" }

[dev-dependencies]
# cargo:1 ends here
